### ISSUE TITLE
Support for Ring Floodlights

### ISSUE THREAD

**Issue by brianmaas** [mpoulson/Indigo-Ring#1]
I just purchased a Ring Floodlight. It has the motion trigger but not a doorbell. It would be great to get support for this type of device. 

I not much of a programmer, but I was going to play around and see if I could get it to work. You don't have the source for ring.py in this repo, only a pyc. Could you add that?

There is another python project to support ring. Here is an issue thread about adding the floodlight to that. https://github.com/tchellomello/python-ring-doorbell/issues/38

**Comment by mpoulson** [comment]
I have included support in v0.1.13.  Please give it a try and let me know.

**Comment by brianmaas** [comment]
Thanks! It works great. Triggers using `lastMotionTime` in Indigo get me what I needed. Turning the floodlight off and on also works. Much appreciated.
