### ISSUE TITLE
Error messages after upgrade from 0.1.17 to 0.1.21

### ISSUE THREAD

**Issue by UberEclectic** [mpoulson/Indigo-Ring#2]
Just upgraded the plugin and am getting continuous errors.
Tried editing each device to see if "NoneType" or other null variant was showing but all looked fine.
Re-saved each device anyway.  No help.
Had to downgrade back to 1.1.17.  

Error messages with device type annotations added by me:

 Enabling plugin "Ring Doorbell 0.1.21"
   Starting plugin "Ring Doorbell 0.1.21" (pid 2351)
   Started plugin "Ring Doorbell 0.1.21"
   Ring Doorbell                   Number of devices found: 5
   Ring Doorbell                   	Front Door (id: 1077313)
   Ring Doorbell                   	Back Yard (id: 4187223) ** Spotlight Cam **
   Ring Doorbell                   	Back Door (id: 4185020) ** Spotlight Cam **
   Ring Doorbell                   	Front Porch (id: 1459869)
   Ring Doorbell                   	Garage (id: 4183919) ** Floodlight Cam **
   Ring Doorbell                   Checking for updates...
   Ring Doorbell                   No updates are available
   Ring Doorbell Error             Failed to get correct event data for deviceID:4185020. Will keep retrying until max attempts (5) reached
   Ring Doorbell Error             Error: int() argument must be a string or a number, not 'NoneType'
   Ring Doorbell Error             Failed to get correct event data for deviceID:4187223. Will keep retrying until max attempts (5) reached
   Ring Doorbell Error             Error: int() argument must be a string or a number, not 'NoneType'
   Ring Doorbell Error             [Mon Jan  8 17:57:45 2018] No value found for device: Ring: Garage, field: batteryLevel
   Ring Doorbell Error             Failed to get correct event data for deviceID:4185020. Will keep retrying until max attempts (5) reached
   Ring Doorbell Error             Error: int() argument must be a string or a number, not 'NoneType'
   Ring Doorbell Error             Failed to get correct event data for deviceID:4187223. Will keep retrying until max attempts (5) reached
   Ring Doorbell Error             Error: int() argument must be a string or a number, not 'NoneType'

**Comment by mpoulson** [comment]
That is not good. I will take a look tonight.  I think I know the issue.  I had to add some support for legacy items that are difficult to test.



Sent from phone. Typos and autocorrect may happen.
________________________________

**Comment by mpoulson** [comment]
version 0.1.23 should resolve this issue.  

Let me know if you have any problems with it.

**Comment by UberEclectic** [comment]
Confirmed all fixed!  You rock!
(Only better than rock!  Ahahaha haha ha!)  =D
