### ISSUE TITLE
State for wrong device captured in _refreshStatesFromHardware

### ISSUE THREAD

**Issue by ZachBenz** [mpoulson/Indigo-Ring#3]
https://github.com/mpoulson/Indigo-Ring/blob/1462e3aca45f17695b05344cd8e392b0a114b4f9/Ring.indigoPlugin/Contents/Server%20Plugin/plugin.py#L47

As I noted in a post on the IndigoDomo user forms, I think there is a bug here.  The problem is that `lastEvents = Ring.GetDoorbellEvent(self.Ring)` appears to get any new events, regardless of which device they might be for.

The if/else logic that follows then incorrectly assigns (in the else) the first event in lastEvents to the device currently having its state refreshed, when that event may in fact be for another device.

In Indigo this manifests itself as the wrong device getting assigned e.g. a lastMotionTime.  The correct device will eventually get the correct state since the if logic also seems to be broken - that is, if no events in lastEvent, then lookup the state for the device (correctly) and assign it.  Thus, depending on timing of the polling update, there is a race condition and you could either see:

- A random other device get updated with another devices state, followed by the correct device getting its state also updated
- Or, if you're lucky, only the correct device getting its state updated (if the timing just so happens to work out that the device with the state update is the next one to get polled)

**Comment by ZachBenz** [comment]
I can't inspect Ring.pyc, so I'm not sure exactly what `Ring.GetDoorbellEvent(self.Ring)` vs `Ring.GetDoorbellEventsforId(self.Ring, doorbellId)` does, but it seems the former gives you only 'new' events?  Thus you can use it to check if there is anything 'new'?  Regardless, the state for the current device shouldn't get pulled from lastEvents, I don't think, but rather from a call to `Ring.GetDoorbellEventsforId(self.Ring, doorbellId)`

**Comment by ZachBenz** [comment]
Perhaps replace:

```
            lastEvents = Ring.GetDoorbellEvent(self.Ring)

            if len(lastEvents) == 0:
                event = Ring.GetDoorbellEventsforId(self.Ring, doorbellId)
            else:
                self.debugLog("Recent Event(s) found!  Count: %s" % len(lastEvents))
                for k, v in lastEvents.iteritems():
                    event = v
                    break
```

with just:

```
            event = Ring.GetDoorbellEventsforId(self.Ring, doorbellId)
```

That is, `lastEvents = Ring.GetDoorbellEvent(self.Ring)` isn't helpful here (I don't think?) because it is getting any new events across **_all_** devices, but inside `_refreshStatesFromHardware` we're only supposed to be updating the current device, not managing global state.

**Comment by ZachBenz** [comment]
One other thought: we could change the way device polling is done in `runConcurrentThread`.  Assuming `lastEvents = Ring.GetDoorbellEvent(self.Ring)` gives us only new, unprocessed events across all devices, we could poll it periodically.  Then, instead of iterating over devices in `runConcurrentThread` and updating each one, we iterate over the contents of lastEvents, processing each event in turn against its associated device (or discarding if there is no Indigo device mapped to that event's Ring device).  This would also greatly reduce the amount of Ring 'API' calls needed (no need to request a device state directly).

Thus, `_refreshStatesFromHardware` wouldn't retrieve anything from Ring, it would just update the specified device within Indigo with the specified state (e.g. passed as an argument).

All that said, perhaps there are state changes not captured in lastEvents (e.g. battery level?) because they aren't notable events like motion or a ring?  For these we would indeed need to poll each device individually for its full state, although perhaps at a lower frequency than the event processing?

**Comment by ZachBenz** [comment]
I verified my suggested fix above works, and created a pull request with the fix.

That said, I think changing the polling could work better (or at least be more efficient) per my comment just before this one.

**Comment by mpoulson** [comment]
Do you want to provide a pull-request with proposed changes or I can make them directly on your behalf.

Sent from phone. Typos and autocorrect may happen.
________________________________

**Comment by ZachBenz** [comment]
Yep, just put in a pull request. :-)

**Comment by mpoulson** [comment]
Your note on moving where we do the global event polling is a good idea.  I will work on that change and verify.

As for this short term fix.  I think there is a different edit needed to still allow the second event API query to be processed in the event there are no global events pending.

Can you test this release? https://github.com/mpoulson/Indigo-Ring/archive/eventfix.zip

I still need to test this on my side.  However I think the change covered in https://github.com/mpoulson/Indigo-Ring/commit/c2e26f18b4a9b562fe27fe2356c0c220ef04e47c
is a better fix as we won't miss other events.

Thoughts?

Also I don't checkin Ring.py because i have my telemetry key in there that I don't want used by others outside my "official" versions.

**Comment by ZachBenz** [comment]
Just installed and tested, and appears to work!

I get what you mean about potentially missing events... e.g. if they happened more often then you caught them in polling the device directly via `GetDoorbellEventsforId`, per my suggested fix.

I think your proposed fix might still miss events in a different way, though.  That said, I don't appreciate what is returned by the 'ding' vs. 'doorbots' Ring client APIs, so I could have this wrong.  In using the 'ding' API, does `GetDoorbellEvent` indeed get all new events?  If so, by processing only the first event you find that matches the current doorbellId, do you end up eating and/or discarding events for other devices, thus missing events?

In the long run, I think the polling based on the global events (vs. by device) would get around all these edge cases/race conditions, allowing you to make an Indigo update for each and every event returned.

But, again, I'm making a lot of assumptions about how the ring API works that I might be completely wrong about!

**Comment by mpoulson** [comment]
You are correct on how the API works.  I plan to spend some time on the fixes this weekend.

Sent from phone. Typos and autocorrect may happen.
________________________________
