### ISSUE TITLE
API request url construction in v.0.1.27's Ring.py's GetRecordingUrl should have disable_redirect=false, not true

### ISSUE THREAD

**Issue by ZachBenz** [mpoulson/Indigo-Ring#8]
See comments recently added to issue #5

**Comment by ZachBenz** [comment]
Did you get a chance to fix this in 0.1.28?

Specifically:

> Ok, the new url construction will also work if you change disable_redirect=true to false; that is, this url construction works in GetRecordingUrl:
> 
> `url = '%sdings/%s/recording?api_version=9&disable_redirect=false&auth_token=%s' % (self.baseUrl, recordingId, self.sessionID)`
> 
> When the redirect disabled, it appears the video itself never gets loaded, and you just get the JSON with the URL. Allowing redirect causes the video content to be retrieved.

**Comment by mpoulson** [comment]
0.1.29 has your fix

**Comment by ZachBenz** [comment]
Thanks!!
